pipeline {
    agent any
    environment {
      VAULT_ADDR = 'https://vault.misaels.eu'
    }

    stages {
        stage('Fetch secrets'){
          steps {
            withVault([
              configuration: [
                vaultUrl: "${env.VAULT_ADDR}", 
                vaultCredentialId: 'vault-jenkins'
              ],
              vaultSecrets: [
                [path: 'secret/ci', secretValues: [
                  [envVar: "TEST_DATA", vaultKey: "TEST"]]]
              ]]
            ) {
              sh '''
                echo $TEST_DATA > /tmp/test_data.txt
                cat /tmp/test_data.txt
                env | grep TEST_DATA
              '''
            }
          }
        }

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                echo "Building the project..."
                // Replace with your build command, e.g.:
                // sh 'mvn clean package'
            }
        }

        stage('SonarQube Analysis') {
            steps {
                script {
                    def scannerHome = tool 'Sonar'
                    withSonarQubeEnv('Sonar') {
                        sh "${scannerHome}/bin/sonar-scanner"
                    }
                }
            }
        }

        // stage('Semgrep Scan') {
        //   environment {
        //     SEMGREP_APP_TOKEN = credentials('SEMGREP_APP_TOKEN')
        //   }
        //
        //   steps {
        //     sh '''
        //       python3 -m venv .venv
        //       . .venv/bin/activate
        //       pip install semgrep
        //       semgrep ci
        //     '''
        //   }
        // }

        stage('Test') {
            steps {
                echo "Running tests..."
                // Replace with your test command, e.g.:
                // sh 'mvn test'
            }
        }

        stage('Deploy') {
            when {
                branch 'main' // Only deploy on main branch
            }
            steps {
                echo "Deploying the project..."
                // Replace with your deployment steps
            }
        }
    }

    post {
        success {
            echo "Pipeline finished successfully!"
        }
        failure {
            echo "Pipeline failed!"
        }
    }
}

