pipeline {
    agent any

    stages {
        environment {
          VAULT_ADDR = 'https://vault.misaels.eu'
        }

        stage('Fetch secrets'){
          steps {
            withVault(
              configuration: [vaultUrl: "${env.VAULT_ADDR}", credentials: 'vault-jenkins']
            )
          
            {
              sh '''
                echo "Test working"
              '''
            }
          }
        }

        stage('Checkout') {
            steps {
                echo "Checking out code..."
		//sshagent(['f8e864e4-84c4-442b-926d-50ac10a1a64f']) {
                //	git branch: 'main', url: 'git@github.com:mps-technologies/mps-portfolio.git' 
		//}
            }
        }

        stage('Build') {
            steps {
                echo "Building the project..."
                // Replace with your build command, e.g.:
                // sh 'mvn clean package'
            }
        }

        stage('Semgrep Scan') {
          environment {
            SEMGREP_APP_TOKEN = credentials('SEMGREP_APP_TOKEN')
          }

          steps {
            sh '''
              python3 -m venv .venv
              . .venv/bin/activate
              pip install semgrep
              semgrep ci
            '''
          }
        }

        stage('Test') {
            steps {
                echo "Running tests..."
                // Replace with your test command, e.g.:
                // sh 'mvn test'
            }
        }

        stage('Deploy') {
            when {
                branch 'main' // Only deploy on main branch
            }
            steps {
                echo "Deploying the project..."
                // Replace with your deployment steps
            }
        }
    }

    post {
        success {
            echo "Pipeline finished successfully!"
        }
        failure {
            echo "Pipeline failed!"
        }
    }
}

